name: Deployment pipeline

on:
  pull_request:
  push:
    branches: [main]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    env:
      working-directory: ./next-app
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.17"

      - name: Install dependencies
        run: npm install
        working-directory: ${{ env.working-directory }}

      - name: Lint
        run: npm run lint
        working-directory: ${{ env.working-directory }}

      - name: Test
        run: npm run build && npm run test
        working-directory: ${{ env.working-directory }}

      # - name: Build
      #   run: npm run build
      #   working-directory: ${{ env.working-directory }}
